import { roboto } from '@/lib/fonts';
import MuiProvider from '@/lib/MuiProvider';
import { Analytics } from '@vercel/analytics/next';
import type { Metadata } from 'next';
import type { ReactNode } from 'react';

import './theme.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html className={roboto.variable} lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <Analytics />

        <MuiProvider>{children}</MuiProvider>
      </body>
    </html>
  );
}

export interface RootLayoutProps {
  readonly children: ReactNode;
}
